### ISSUE TITLE
Test stats

### ISSUE THREAD

**Issue by MarnickGoossens** [takis-mosa/prog2-exercises#5]
Als resultaat vraagt u in de opgave een lijst maar in uw testen staat bij u assert alles tussen haakjes dus is dat geen lijst.

**Comment by takis-mosa** [comment]
Bedankt voor het melden @MarnickGoossens !

Ik heb de code aangepast, en door te verwijzen naar deze issue in de commit-messages wordt de issue automatisch gesloten door GitHub (door de vermelding van "fixes").

In mijn oplossing gaf ik een tuple terug ipv een lijst. Tuples kan je zien als niet-aanpasbare lijsten. Maar in de documentatie van de code gaf ik expliciet aan dat een lijst teruggegeven moest worden, dus was de test inderdaad fout.
